### ISSUE TITLE
Anclado AnaItem

### ISSUE THREAD

**Issue by gromero01** [SUB-ESTADISTICA-ICFES/ACC#7]
1. En los crear datBlock al nombre del archivo también le está pegando en nombre de la carpeta:

i.e.: datBlock_PBAF500301_exam752_V1

2. Adicional, no encuentra un argumento "times":

...... Lecutura de la forma pbaF500301 
...... del archivo: ../LineaBase/outList_IRT_20164.Rdata 
Transformacion con : ../LineaBase/outList_IRT_20164.Rdata 
.... Ejecutando estimación para --> pbaF500301 
Error in rep(" ", auxLength) : argumento 'times' inválido

**Comment by JoraJora** [comment]
Solucionado por Robert Romero
